### ISSUE TITLE
Incomplete Readme

### ISSUE THREAD

**Issue by febbraiod** [learn-co-curriculum/SQL-bear-organizer-lab#22]
Hello, for one of the methods in the lab you need to use either "GROUP BY" or "MAX" and neither is mentioned in the lesson.  I found them both in the extra resources but the info is buried pretty deep and harder to understand than learn usually makes it. - Don

**Comment by AnnJohn** [comment]
Hi @febbraiod thanks for raising this. The lesson that comes after this one covers MAX, so we'll move the order around but will keep this issue open and will update this specific lesson when we can. Thanks again.

**Comment by AnnJohn** [comment]
@vicfriedman for this, maybe just add a note to students to google these methods instead of explaining them.
