### ISSUE TITLE
incorrect file structure preview in readme

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/SQL-bear-organizer-lab#23]
the file structure preview in the readme is not the same as the file structure in the forked lab. 
├── Gemfile
├── README.md
├── bin
│   ├── environment.rb # requires bundler and files
│   ├── run.rb # instantiates the SQLRunner class in the below file
│   └── sql_runner.rb # holds a class that handles executing your .sql files
├── lib
│   ├── create.sql # where you create your schema
│   ├── decoded_data.sql # this file we're using to run the tests
│   └── insert.sql # where you insert your data
│   └── sql_queries.rb # where you write your sql queries
└── spec # all the specs
    ├── create_spec.rb # this tests your create.sql file
    ├── insert_spec.rb # this tests your insert.sql file
    ├── select_spec.rb # this tests the queries you write in this file
    └── spec_helper.rb

This is the filestructure preview in the readme when the lib directory looks has
 create.sql
insert.sql
seed.sql
sql
sql_queries.sql

**Comment by AnnJohn** [comment]
hi @pajamaw are you using nitrous? this might be a nitrous issue

**Comment by pajamaw** [comment]
Hi! Nope im local. the fork i cloned didn't contain one of the files the 
readme said it had.
