### ISSUE TITLE
Move instruction/explanation into previous lesson

### ISSUE THREAD

**Issue by AdamKing0126** [learn-co-curriculum/SQL-bear-organizer-lab#25]
A lot of the information here would've been useful in the first lab - where to write SQL queries, etc.

**Comment by AnnJohn** [comment]
thanks for raising this issue @AdamKing0126. Which specific lab are you referring to? The lessons before this are Readmes or Codealongs where we walk you through the content.

**Comment by AdamKing0126** [comment]
Ann,

The first lab where we actually write SQL and pass tests is "SQL Aggregate
Functions Lab" and the only instructions provided are "Run learn to get
started. Write your SQL in lib/students to get the specs in
spec/student_spec.rb to pass."

Then, the next lab, "SQL Bear Organizer" it includes these instructions:

Part 3: SELECT

Get the tests in spec/select_spec.rb to pass. Note that for this section,
the database will be seeded with external data from the lib/seed.sql file
so don't expect it to reflect the data you added above. Note: Since it's a
Ruby file, write your queries as strings in the lib/sql_queries.rb.

This was the part I had difficulty with in the first lab.  Where do I write
my SQL code? How do I write my SQL code into a Ruby file?  I found out
after asking on the slack channel, I think, but it'd be nice to just have
that info inside the lab instructions.

In the lessons and codealongs proceeding the SQL aggregate functions lab,
we never wrote code into a .rb file.

Best,

Adam

On Thu, Feb 4, 2016 at 4:42 PM, AnnJohn <notifications@github.com> wrote:
>
> thanks for raising this issue @AdamKing0126. Which specific lab are you
referring to? The lessons before this are Readmes or Codealongs where we
walk you through the content.

**Comment by vicfriedman** [comment]
closing this issue and opening one on the sql-aggregate lab
