### ISSUE TITLE
Mismatched title

### ISSUE THREAD

**Issue by brianmenard** [learn-co-curriculum/SQL-bear-organizer-lab#28]
My pull request isn't working, I believe because the links to github and the fork from the learn page are linking to SQL-bear-organizer-lab-v-000, but the repo is actually titled SQL-bear-organizer-v-000 on github, so the links are broken

**Comment by vicfriedman** [comment]
hey @brianmenard,

can you open a bug report? That seems like a engineering issue, and less of a a curriculum issue. I'm going to go ahead and close this.

Thanks!
