### ISSUE TITLE
select_spec.rb final test seems to never pass

### ISSUE THREAD

**Issue by ivsuleman** [learn-co-curriculum/SQL-bear-organizer-lab#37]
"SELECT * FROM bears WHERE bears.name IS NULL;" 

     expected: [[8, nil, 20, "M", "black", "aggressive", 0]]
            got: [[8, nil, 20, "M", "black", "aggressive", "0"]]

**Comment by jenmyers** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
